import { BudgetLineDocument } from '../models/budget';
import { Typology } from '../models/engineering';

// Necesario para usar Typology como VALUE
const T = Typology;

// ═══════════════════════════════════════════════════════════════════════════════
//  RESIDENCIAL — 40 RENGLONES EN ORDEN CRONOLÓGICO
// ═══════════════════════════════════════════════════════════════════════════════

export const RESIDENCIAL_LINES: BudgetLineDocument[] = [

  // ═══ PRELIMINARES ═════════════════════════════════════════════════════════
  {
    id:'res_preliminary_001', code:'PRE-001',
    description:'Limpieza y chapeo del terreno',
    unit:'m2', category:'Preliminares', typology:T.RESIDENCIAL,
    order:1, isActive:true, projectQuantity:0, computationType:'fixed' as const,
    dimensions:undefined,
    materials:[
      {name:'Combustible motosierra',unit:'lt',quantity:0.05,unitPrice:12,wasteFactor:1,totalCost:0.6},
      {name:'Herramienta manual (pico, pala)',unit:'global',quantity:0.02,unitPrice:250,wasteFactor:1,totalCost:5},
    ],
    labor:[
      {role:'Peón',quantity:0.05,dailyWage:85,totalCost:4.25},
    ],
    equipment:[],
    dailyOutput:15, crewSize:2, durationDays:0,
    children:[],
  },
  {
    id:'res_preliminary_002', code:'PRE-002',
    description:'Trazo y estaqueado',
    unit:'m2', category:'Preliminares', typology:T.RESIDENCIAL,
    order:2, isActive:true, projectQuantity:0, computationType:'fixed' as const,
    dimensions:undefined,
    materials:[
      {name:'Estacas madera 2x2"',unit:'un',quantity:20,unitPrice:3,wasteFactor:1.05,totalCost:63},
      {name:'Hilo nylon 200m',unit:'rollo',quantity:0.1,unitPrice:45,wasteFactor:1,totalCost:4.5},
      {name:'Clavos 3"',unit:'kg',quantity:0.5,unitPrice:18,wasteFactor:1,totalCost:9},
    ],
    labor:[
      {role:'Peón',quantity:0.05,dailyWage:85,totalCost:4.25},
      {role:'Ayudante',quantity:0.03,dailyWage:75,totalCost:2.25},
    ],
    equipment:[],
    dailyOutput:20, crewSize:2, durationDays:0,
    children:[],
  },
  {
    id:'res_preliminary_003', code:'PRE-003',
    description:'Cerramiento provisional de madera',
    unit:'ml', category:'Preliminares', typology:T.RESIDENCIAL,
    order:3, isActive:true, projectQuantity:0, computationType:'fixed' as const,
    dimensions:undefined,
    materials:[
      {name:'Tabla madera 2x4x3m',unit:'ml',quantity:0.4,unitPrice:45,wasteFactor:1.10,totalCost:19.8},
      {name:'Clavos 3" (kg)',unit:'kg',quantity:0.3,unitPrice:18,wasteFactor:1,totalCost:5.4},
      {name:'Alambre recocido No.16 (kg)',unit:'kg',quantity:0.3,unitPrice:8,wasteFactor:1,totalCost:2.4},
    ],
    labor:[
      {role:'Carpintero',quantity:0.15,dailyWage:155,totalCost:23.25},
      {role:'Peón',quantity:0.1,dailyWage:85,totalCost:8.5},
    ],
    equipment:[],
    dailyOutput:8, crewSize:2, durationDays:0,
    children:[],
  },
  {
    id:'res_preliminary_004', code:'PRE-004',
    description:'Bodega provisional de obra',
    unit:'un', category:'Preliminares', typology:T.RESIDENCIAL,
    order:4, isActive:true, projectQuantity:0, computationType:'fixed' as const,
    dimensions:undefined,
    materials:[
      {name:'Lámina de zinc calibre 26 (m2)',unit:'m2',quantity:8,unitPrice:35,wasteFactor:1.05,totalCost:294},
      {name:'Madera 2x4x3m (ml)',unit:'ml',quantity:8,unitPrice:45,wasteFactor:1.05,totalCost:378},
      {name:'Clavos 3" (kg)',unit:'kg',quantity:1,unitPrice:18,wasteFactor:1,totalCost:18},
      {name:'Tornillos 3" (un)',unit:'un',quantity:50,unitPrice:0.8,wasteFactor:1,totalCost:40},
    ],
    labor:[
      {role:'Carpintero',quantity:0.5,dailyWage:155,totalCost:77.5},
      {role:'Ayudante',quantity:0.5,dailyWage:75,totalCost:37.5},
    ],
    equipment:[],
    dailyOutput:1, crewSize:3, durationDays:1,
    children:[],
  },

  // ═══ CIMENTACIÓN ═════════════════════════════════════════════════════════
  {
    id:'res_foundation_001', code:'CIM-001',
    description:'Cimentación - Excavación y Relleno',
    unit:'m3', category:'Cimentación', typology:T.RESIDENCIAL,
    order:5, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,height:0},
    materials:[
      {name:'Excavación manual - Herramienta (pico, pala, carretilla)',unit:'global',quantity:0.03,unitPrice:450,wasteFactor:1,totalCost:13.5},
    ],
    labor:[
      {role:'Peón',quantity:0.5,dailyWage:85,totalCost:42.5},
    ],
    equipment:[],
    dailyOutput:5, crewSize:3, durationDays:0,
    children:[],
  },
  {
    id:'res_foundation_002', code:'CIM-002',
    description:'Cimentación - Relleno y compactación manual',
    unit:'m3', category:'Cimentación', typology:T.RESIDENCIAL,
    order:6, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,height:0},
    materials:[
      {name:'Material selecto de relleno (m3)',unit:'m3',quantity:1,unitPrice:22,wasteFactor:1,totalCost:22},
      {name:'Compactación manual',unit:'global',quantity:1,unitPrice:15,wasteFactor:1,totalCost:15},
    ],
    labor:[
      {role:'Peón',quantity:0.3,dailyWage:85,totalCost:25.5},
    ],
    equipment:[],
    dailyOutput:4, crewSize:2, durationDays:0,
    children:[],
  },
  {
    id:'res_foundation_003', code:'CIM-003',
    description:"Solado de limpieza f'c=140 kg/cm²",
    unit:'m2', category:'Cimentación', typology:T.RESIDENCIAL,
    order:7, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,thickness:0.10},
    materials:[
      {name:"Concreto f'c 140",unit:'m3',quantity:0.1,unitPrice:450,wasteFactor:1.03,totalCost:46.35},
    ],
    labor:[
      {role:'Maestro de obras',quantity:0.15,dailyWage:185,totalCost:27.75},
      {role:'Albañil',quantity:0.2,dailyWage:145,totalCost:29},
      {role:'Peón',quantity:0.3,dailyWage:85,totalCost:25.5},
    ],
    equipment:[],
    dailyOutput:8, crewSize:3, durationDays:0,
    children:[],
  },
  {
    id:'res_foundation_004', code:'CIM-004',
    description:"Zapata aislada f'c=210 kg/cm²",
    unit:'m3', category:'Cimentación', typology:T.RESIDENCIAL,
    order:8, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,height:0},
    materials:[
      {name:"Concreto f'c 210",unit:'m3',quantity:1,unitPrice:520,wasteFactor:1.03,totalCost:535.6},
      {name:'Cemento Portland tipo I (saco 42.5kg)',unit:'saco',quantity:8.5,unitPrice:62,wasteFactor:1.02,totalCost:536.14},
      {name:'Arena de río lavada',unit:'m3',quantity:0.45,unitPrice:185,wasteFactor:1,totalCost:83.25},
      {name:'Grava triturada 3/4"',unit:'m3',quantity:0.65,unitPrice:210,wasteFactor:1,totalCost:136.5},
      {name:'Agua potable',unit:'m3',quantity:0.18,unitPrice:8,wasteFactor:1,totalCost:1.44},
      {name:'Formaleta madera pino (m2)',unit:'m2',quantity:4,unitPrice:45,wasteFactor:1.02,totalCost:183.6},
      {name:'Desmoldante (lt)',unit:'lt',quantity:0.5,unitPrice:28,wasteFactor:1,totalCost:14},
    ],
    labor:[
      {role:'Maestro de obras',quantity:0.5,dailyWage:185,totalCost:92.5},
      {role:'Albañil',quantity:1,dailyWage:145,totalCost:145},
      {role:'Peón',quantity:2,dailyWage:85,totalCost:170},
    ],
    equipment:[],
    dailyOutput:2, crewSize:4, durationDays:3,
    children:[],
  },
  {
    id:'res_foundation_005', code:'CIM-005',
    description:"Viga de cimentación f'c=210 kg/cm²",
    unit:'m3', category:'Cimentación', typology:T.RESIDENCIAL,
    order:9, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,height:0},
    materials:[
      {name:"Concreto f'c 210",unit:'m3',quantity:1,unitPrice:520,wasteFactor:1.03,totalCost:535.6},
      {name:'Cemento Portland tipo I (saco 42.5kg)',unit:'saco',quantity:7.5,unitPrice:62,wasteFactor:1.02,totalCost:465},
      {name:'Arena de río lavada',unit:'m3',quantity:0.4,unitPrice:185,wasteFactor:1,totalCost:74},
      {name:'Grava triturada 3/4"',unit:'m3',quantity:0.58,unitPrice:210,wasteFactor:1,totalCost:121.8},
      {name:'Acero de refuerzo No.3 (3/8") (kg)',unit:'kg',quantity:65,unitPrice:10.5,wasteFactor:1.05,totalCost:719.25},
      {name:'Alambre de amarre No.18 (kg)',unit:'kg',quantity:1.2,unitPrice:12,wasteFactor:1,totalCost:14.4},
      {name:'Formaleta metálica (m2)',unit:'m2',quantity:5,unitPrice:85,wasteFactor:1.02,totalCost:433.5},
      {name:'Desmoldante (lt)',unit:'lt',quantity:0.4,unitPrice:28,wasteFactor:1,totalCost:11.2},
    ],
    labor:[
      {role:'Maestro de obras',quantity:0.6,dailyWage:185,totalCost:111},
      {role:'Acerista',quantity:0.5,dailyWage:165,totalCost:82.5},
      {role:'Albañil',quantity:1,dailyWage:145,totalCost:145},
      {role:'Peón',quantity:2,dailyWage:85,totalCost:170},
    ],
    equipment:[],
    dailyOutput:1.5, crewSize:5, durationDays:2,
    children:[],
  },
  {
    id:'res_foundation_006', code:'CIM-006',
    description:'Acero de refuerzo No.3 (3/8") - Colocación',
    unit:'kg', category:'Cimentación', typology:T.RESIDENCIAL,
    order:10, isActive:true, projectQuantity:0, computationType:'fixed' as const,
    dimensions:undefined,
    materials:[
      {name:'Acero de refuerzo No.3 (3/8") barras 6m',unit:'kg',quantity:1,unitPrice:10.5,wasteFactor:1.05,totalCost:11.025},
      {name:'Alambre de atar No.16 recocido (kg)',unit:'kg',quantity:0.05,unitPrice:12,wasteFactor:1,totalCost:0.6},
      {name:'Separadores de concreto (un)',unit:'un',quantity:5,unitPrice:0.5,wasteFactor:1,totalCost:2.5},
    ],
    labor:[
      {role:'Acerista',quantity:0.15,dailyWage:165,totalCost:24.75},
      {role:'Ayudante',quantity:0.1,dailyWage:75,totalCost:7.5},
    ],
    equipment:[],
    dailyOutput:50, crewSize:2, durationDays:0,
    children:[],
  },

  // ═══ ESTRUCTURA ═══════════════════════════════════════════════════════════
  {
    id:'res_structure_001', code:'EST-001',
    description:'Columna principal de concreto armado f\'c=210 kg/cm²',
    unit:'m3', category:'Estructura', typology:T.RESIDENCIAL,
    order:11, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,height:0},
    materials:[
      {name:"Concreto f'c 210",unit:'m3',quantity:1,unitPrice:520,wasteFactor:1.03,totalCost:535.6},
      {name:'Cemento Portland tipo I (saco 42.5kg)',unit:'saco',quantity:7,unitPrice:62,wasteFactor:1.02,totalCost:442.68},
      {name:'Arena de río lavada',unit:'m3',quantity:0.35,unitPrice:185,wasteFactor:1,totalCost:64.75},
      {name:'Grava triturada 3/4"',unit:'m3',quantity:0.5,unitPrice:210,wasteFactor:1,totalCost:105},
      {name:'Acero de refuerzo No.4 (1/2") (kg)',unit:'kg',quantity:55,unitPrice:11.5,wasteFactor:1.05,totalCost:666.375},
      {name:'Acero de refuerzo No.3 (3/8") (kg)',unit:'kg',quantity:25,unitPrice:10.5,wasteFactor:1.05,totalCost:275.625},
      {name:'Alambre de amarre No.18 (kg)',unit:'kg',quantity:2,unitPrice:12,wasteFactor:1,totalCost:24},
      {name:'Formaleta metálica columna (m2)',unit:'m2',quantity:8,unitPrice:85,wasteFactor:1.02,totalCost:693.6},
      {name:'Desmoldante (lt)',unit:'lt',quantity:0.6,unitPrice:28,wasteFactor:1,totalCost:16.8},
    ],
    labor:[
      {role:'Maestro de obras',quantity:0.8,dailyWage:185,totalCost:148},
      {role:'Albañil',quantity:1.5,dailyWage:145,totalCost:217.5},
      {role:'Acerista',quantity:0.6,dailyWage:165,totalCost:99},
      {role:'Peón',quantity:3,dailyWage:85,totalCost:255},
    ],
    equipment:[],
    dailyOutput:0.5, crewSize:6, durationDays:3,
    children:[],
  },
  {
    id:'res_structure_002', code:'EST-002',
    description:'Viga de amarre f\'c=210 kg/cm²',
    unit:'m3', category:'Estructura', typology:T.RESIDENCIAL,
    order:12, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,height:0},
    materials:[
      {name:"Concreto f'c 210",unit:'m3',quantity:1,unitPrice:520,wasteFactor:1.03,totalCost:535.6},
      {name:'Cemento Portland tipo I (saco 42.5kg)',unit:'saco',quantity:6.5,unitPrice:62,wasteFactor:1.02,totalCost:410.14},
      {name:'Arena de río lavada',unit:'m3',quantity:0.32,unitPrice:185,wasteFactor:1,totalCost:59.2},
      {name:'Grava triturada 3/4"',unit:'m3',quantity:0.47,unitPrice:210,wasteFactor:1,totalCost:98.7},
      {name:'Acero de refuerzo No.4 (1/2") (kg)',unit:'kg',quantity:35,unitPrice:11.5,wasteFactor:1.05,totalCost:422.625},
      {name:'Acero de refuerzo No.3 (3/8") (kg)',unit:'kg',quantity:15,unitPrice:10.5,wasteFactor:1.05,totalCost:165.375},
      {name:'Alambre de amarre No.18 (kg)',unit:'kg',quantity:1,unitPrice:12,wasteFactor:1,totalCost:12},
      {name:'Formaleta metálica (m2)',unit:'m2',quantity:6,unitPrice:85,wasteFactor:1.02,totalCost:520.2},
      {name:'Desmoldante (lt)',unit:'lt',quantity:0.4,unitPrice:28,wasteFactor:1,totalCost:11.2},
    ],
    labor:[
      {role:'Maestro de obras',quantity:0.6,dailyWage:185,totalCost:111},
      {role:'Albañil',quantity:1.2,dailyWage:145,totalCost:174},
      {role:'Acerista',quantity:0.5,dailyWage:165,totalCost:82.5},
      {role:'Peón',quantity:2,dailyWage:85,totalCost:170},
    ],
    equipment:[],
    dailyOutput:1.5, crewSize:5, durationDays:2,
    children:[],
  },
  {
    id:'res_structure_003', code:'EST-003',
    description:'Losa maciza entrepiso e=0.12m',
    unit:'m2', category:'Estructura', typology:T.RESIDENCIAL,
    order:13, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,thickness:0.12},
    materials:[
      {name:"Concreto f'c 210",unit:'m3',quantity:0.12,unitPrice:520,wasteFactor:1.03,totalCost:64.296},
      {name:'Cemento Portland tipo I 42.5kg',unit:'saco',quantity:1.1,unitPrice:62,wasteFactor:1.02,totalCost:69.484},
      {name:'Arena de río lavada',unit:'m3',quantity:0.055,unitPrice:185,wasteFactor:1,totalCost:10.175},
      {name:'Grava triturada 3/4"',unit:'m3',quantity:0.08,unitPrice:210,wasteFactor:1,totalCost:16.8},
      {name:'Acero de refuerzo No.3 (3/8") (kg)',unit:'kg',quantity:8,unitPrice:10.5,wasteFactor:1.05,totalCost:88.2},
      {name:'Formaleta madera pino (m2)',unit:'m2',quantity:1.1,unitPrice:45,wasteFactor:1.03,totalCost:50.985},
      {name:'Puntales metálicos (un)',unit:'un',quantity:0.15,unitPrice:185,wasteFactor:1,totalCost:27.75},
    ],
    labor:[
      {role:'Maestro de obras',quantity:0.12,dailyWage:185,totalCost:22.2},
      {role:'Albañil',quantity:0.25,dailyWage:145,totalCost:36.25},
      {role:'Peón',quantity:0.5,dailyWage:85,totalCost:42.5},
    ],
    equipment:[],
    dailyOutput:8, crewSize:3, durationDays:1,
    children:[],
  },
  {
    id:'res_structure_004', code:'EST-004',
    description:'Acero de refuerzo No.4 (1/2") - Colocación',
    unit:'kg', category:'Estructura', typology:T.RESIDENCIAL,
    order:14, isActive:true, projectQuantity:0, computationType:'fixed' as const,
    dimensions:undefined,
    materials:[
      {name:'Acero de refuerzo No.4 (1/2") barras 12m',unit:'kg',quantity:1,unitPrice:11.5,wasteFactor:1.05,totalCost:12.075},
      {name:'Alambre de atar No.16 recocido (kg)',unit:'kg',quantity:0.06,unitPrice:12,wasteFactor:1,totalCost:0.72},
      {name:'Separadores de concreto (un)',unit:'un',quantity:6,unitPrice:0.5,wasteFactor:1,totalCost:3},
    ],
    labor:[
      {role:'Acerista',quantity:0.15,dailyWage:165,totalCost:24.75},
      {role:'Ayudante',quantity:0.1,dailyWage:75,totalCost:7.5},
    ],
    equipment:[],
    dailyOutput:50, crewSize:2, durationDays:0,
    children:[],
  },
  {
    id:'res_structure_005', code:'EST-005',
    description:'Escalera de concreto armado',
    unit:'m3', category:'Estructura', typology:T.RESIDENCIAL,
    order:15, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,height:0},
    materials:[
      {name:"Concreto f'c 210",unit:'m3',quantity:1,unitPrice:520,wasteFactor:1.03,totalCost:535.6},
      {name:'Cemento Portland tipo I 42.5kg',unit:'saco',quantity:9,unitPrice:62,wasteFactor:1.02,totalCost:566.28},
      {name:'Arena de río lavada',unit:'m3',quantity:0.45,unitPrice:185,wasteFactor:1,totalCost:83.25},
      {name:'Grava triturada 3/4"',unit:'m3',quantity:0.65,unitPrice:210,wasteFactor:1,totalCost:136.5},
      {name:'Acero de refuerzo No.4 (1/2") (kg)',unit:'kg',quantity:25,unitPrice:11.5,wasteFactor:1.05,totalCost:301.875},
      {name:'Acero de refuerzo No.3 (3/8") (kg)',unit:'kg',quantity:15,unitPrice:10.5,wasteFactor:1.05,totalCost:165.375},
      {name:'Formaleta metálica escalera (m2)',unit:'m2',quantity:7,unitPrice:85,wasteFactor:1.02,totalCost:606.9},
      {name:'Desmoldante (lt)',unit:'lt',quantity:0.5,unitPrice:28,wasteFactor:1,totalCost:14},
      {name:'Barandal temporal (ml)',unit:'ml',quantity:8,unitPrice:35,wasteFactor:1,totalCost:280},
    ],
    labor:[
      {role:'Maestro de obras',quantity:0.8,dailyWage:185,totalCost:148},
      {role:'Albañil',quantity:2,dailyWage:145,totalCost:290},
      {role:'Acerista',quantity:0.6,dailyWage:165,totalCost:99},
      {role:'Peón',quantity:3,dailyWage:85,totalCost:255},
    ],
    equipment:[],
    dailyOutput:4, crewSize:5, durationDays:4,
    children:[],
  },

  // ═══ MAMPOSTERÍA ═════════════════════════════════════════════════════════
  {
    id:'res_masonry_001', code:'MAM-001',
    description:'Muro de bloque pómez No.4 (0.10m)',
    unit:'m2', category:'Mampostería', typology:T.RESIDENCIAL,
    order:16, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,height:0,thickness:0.10},
    materials:[
      {name:'Bloque pómez No.4 0.10x0.20x0.40m',unit:'un',quantity:12.5,unitPrice:4.5,wasteFactor:1.10,totalCost:61.875},
      {name:'Cemento Portland tipo I 42.5kg',unit:'saco',quantity:0.25,unitPrice:62,wasteFactor:1.05,totalCost:16.275},
      {name:'Arena amarilla para pega (m3)',unit:'m3',quantity:0.02,unitPrice:145,wasteFactor:1,totalCost:2.9},
      {name:'Acero de refuerzo No.3 (3/8") (kg)',unit:'kg',quantity:1.8,unitPrice:10.5,wasteFactor:1.05,totalCost:19.845},
    ],
    labor:[
      {role:'Albañil',quantity:0.2,dailyWage:145,totalCost:29},
      {role:'Peón',quantity:0.15,dailyWage:85,totalCost:12.75},
    ],
    equipment:[],
    dailyOutput:6, crewSize:2, durationDays:0.3,
    children:[],
  },
  {
    id:'res_masonry_002', code:'MAM-002',
    description:'Muro de bloque pómez No.5 (0.15m)',
    unit:'m2', category:'Mampostería', typology:T.RESIDENCIAL,
    order:17, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,height:0,thickness:0.15},
    materials:[
      {name:'Bloque pómez No.5 0.15x0.20x0.40m',unit:'un',quantity:8.33,unitPrice:5.5,wasteFactor:1.10,totalCost:50.415},
      {name:'Cemento Portland tipo I 42.5kg',unit:'saco',quantity:0.35,unitPrice:62,wasteFactor:1.05,totalCost:22.785},
      {name:'Arena amarilla para pega (m3)',unit:'m3',quantity:0.03,unitPrice:145,wasteFactor:1,totalCost:4.35},
      {name:'Acero de refuerzo No.3 (3/8") (kg)',unit:'kg',quantity:2.2,unitPrice:10.5,wasteFactor:1.05,totalCost:24.255},
    ],
    labor:[
      {role:'Albañil',quantity:0.25,dailyWage:145,totalCost:36.25},
      {role:'Peón',quantity:0.18,dailyWage:85,totalCost:15.3},
    ],
    equipment:[],
    dailyOutput:5, crewSize:2, durationDays:0.35,
    children:[],
  },
  {
    id:'res_masonry_003', code:'MAM-003',
    description:'Dintel de concreto armado',
    unit:'ml', category:'Mampostería', typology:T.RESIDENCIAL,
    order:18, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,height:0.15},
    materials:[
      {name:"Concreto f'c 210",unit:'m3',quantity:0.015,unitPrice:520,wasteFactor:1.03,totalCost:8.034},
      {name:'Cemento Portland tipo I 42.5kg',unit:'saco',quantity:0.1,unitPrice:62,wasteFactor:1.02,totalCost:6.324},
      {name:'Arena de río lavada',unit:'m3',quantity:0.005,unitPrice:185,wasteFactor:1,totalCost:0.925},
      {name:'Grava triturada 3/4"',unit:'m3',quantity:0.007,unitPrice:210,wasteFactor:1,totalCost:1.47},
      {name:'Acero de refuerzo No.3 (3/8") (kg)',unit:'kg',quantity:2.5,unitPrice:10.5,wasteFactor:1.05,totalCost:27.5625},
      {name:'Formaleta madera pino (m2)',unit:'m2',quantity:0.3,unitPrice:45,wasteFactor:1,totalCost:13.5},
    ],
    labor:[
      {role:'Albañil',quantity:0.15,dailyWage:145,totalCost:21.75},
      {role:'Peón',quantity:0.1,dailyWage:85,totalCost:8.5},
    ],
    equipment:[],
    dailyOutput:10, crewSize:2, durationDays:0.2,
    children:[],
  },
  {
    id:'res_masonry_004', code:'MAM-004',
    description:'Solera hidrófuga',
    unit:'ml', category:'Mampostería', typology:T.RESIDENCIAL,
    order:19, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,height:0},
    materials:[
      {name:"Concreto f'c 210 con aditivo impermeabilizante",unit:'m3',quantity:0.015,unitPrice:580,wasteFactor:1.03,totalCost:8.931},
      {name:'Cemento Portland tipo I 42.5kg',unit:'saco',quantity:0.1,unitPrice:62,wasteFactor:1.02,totalCost:6.324},
      {name:'Arena de río lavada',unit:'m3',quantity:0.005,unitPrice:185,wasteFactor:1,totalCost:0.925},
      {name:'Aditivo impermeabilizante (lt)',unit:'lt',quantity:0.3,unitPrice:55,wasteFactor:1,totalCost:16.5},
      {name:'Acero de refuerzo No.3 (3/8") (kg)',unit:'kg',quantity:1.5,unitPrice:10.5,wasteFactor:1.05,totalCost:16.5375},
      {name:'Formaleta madera pino (m2)',unit:'m2',quantity:0.2,unitPrice:45,wasteFactor:1,totalCost:9},
      {name:'Membrana asfáltica (ml)',unit:'ml',quantity:0.2,unitPrice:25,wasteFactor:1,totalCost:5},
    ],
    labor:[
      {role:'Albañil',quantity:0.18,dailyWage:145,totalCost:26.1},
      {role:'Peón',quantity:0.12,dailyWage:85,totalCost:10.2},
    ],
    equipment:[],
    dailyOutput:8, crewSize:2, durationDays:0.25,
    children:[],
  },
  {
    id:'res_masonry_005', code:'MAM-005',
    description:'Solera corona',
    unit:'ml', category:'Mampostería', typology:T.RESIDENCIAL,
    order:20, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,height:0.12},
    materials:[
      {name:"Concreto f'c 210",unit:'m3',quantity:0.012,unitPrice:520,wasteFactor:1.03,totalCost:6.4272},
      {name:'Cemento Portland tipo I 42.5kg',unit:'saco',quantity:0.08,unitPrice:62,wasteFactor:1.02,totalCost:5.0592},
      {name:'Arena de río lavada',unit:'m3',quantity:0.004,unitPrice:185,wasteFactor:1,totalCost:0.74},
      {name:'Grava triturada 3/4"',unit:'m3',quantity:0.006,unitPrice:210,wasteFactor:1,totalCost:1.26},
      {name:'Acero de refuerzo No.3 (3/8") (kg)',unit:'kg',quantity:1.8,unitPrice:10.5,wasteFactor:1.05,totalCost:19.845},
      {name:'Formaleta madera pino (m2)',unit:'m2',quantity:0.25,unitPrice:45,wasteFactor:1,totalCost:11.25},
    ],
    labor:[
      {role:'Albañil',quantity:0.15,dailyWage:145,totalCost:21.75},
      {role:'Peón',quantity:0.1,dailyWage:85,totalCost:8.5},
    ],
    equipment:[],
    dailyOutput:10, crewSize:2, durationDays:0.2,
    children:[],
  },

  // ═══ INSTALACIONES ELÉCTRICAS ═══════════════════════════════════════════
  {
    id:'res_electrical_001', code:'INS-001',
    description:'Instalación eléctrica principal',
    unit:'global', category:'Instalaciones', typology:T.RESIDENCIAL,
    order:21, isActive:true, projectQuantity:0, computationType:'fixed' as const,
    dimensions:undefined,
    materials:[
      {name:'Cable THW 12 cal.8 (mt)',unit:'ml',quantity:8,unitPrice:28,wasteFactor:1.05,totalCost:235.2},
      {name:'Cable THW 14 cal.12 (mt)',unit:'ml',quantity:10,unitPrice:18,wasteFactor:1.05,totalCost:189},
      {name:'Ducto conduit PVC 3/4" (ml)',unit:'ml',quantity:5,unitPrice:12,wasteFactor:1.05,totalCost:63},
      {name:'Tinaco 1,100 lts',unit:'un',quantity:1,unitPrice:1850,wasteFactor:1,totalCost:1850},
      {name:'Bomba de agua 1/2 HP',unit:'un',quantity:1,unitPrice:2800,wasteFactor:1,totalCost:2800},
    ],
    labor:[
      {role:'Electricista',quantity:1.5,dailyWage:195,totalCost:292.5},
      {role:'Plomero',quantity:1,dailyWage:155,totalCost:155},
      {role:'Peón',quantity:1,dailyWage:85,totalCost:85},
    ],
    equipment:[],
    dailyOutput:1, crewSize:2, durationDays:1,
    children:[],
  },
  {
    id:'res_electrical_002', code:'INS-002',
    description:'Tablero eléctrico 12 circuitos',
    unit:'un', category:'Instalaciones', typology:T.RESIDENCIAL,
    order:22, isActive:true, projectQuantity:0, computationType:'fixed' as const,
    dimensions:undefined,
    materials:[
      {name:'Tablero metálico 12 circuitos',unit:'un',quantity:1,unitPrice:480,wasteFactor:1,totalCost:480},
      {name:'Breaker 20A bipolar (un)',unit:'un',quantity:8,unitPrice:35,wasteFactor:1,totalCost:280},
      {name:'Breaker 15A bipolar (un)',unit:'un',quantity:4,unitPrice:30,wasteFactor:1,totalCost:120},
      {name:'Contacto sencillo 120V con caja',unit:'un',quantity:12,unitPrice:25,wasteFactor:1,totalCost:300},
    ],
    labor:[
      {role:'Electricista',quantity:1,dailyWage:195,totalCost:195},
      {role:'Peón',quantity:0.5,dailyWage:85,totalCost:42.5},
    ],
    equipment:[],
    dailyOutput:1, crewSize:2, durationDays:1,
    children:[],
  },

  // ═══ INSTALACIONES SANITARIAS ═══════════════════════════════════════════
  {
    id:'res_plumbing_001', code:'INS-003',
    description:'Instalación sanitaria PVC 4"',
    unit:'ml', category:'Instalaciones', typology:T.RESIDENCIAL,
    order:23, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0},
    materials:[
      {name:'Tubería PVC sanitaria 4" (6m)',unit:'un',quantity:0.17,unitPrice:185,wasteFactor:1.05,totalCost:32.9925},
      {name:'Codo PVC 4" x 90°',unit:'un',quantity:0.1,unitPrice:28,wasteFactor:1,totalCost:2.8},
      {name:'Yee PVC 4"',unit:'un',quantity:0.05,unitPrice:35,wasteFactor:1,totalCost:1.75},
      {name:'Pegamento PVC (1/4 lt)',unit:'un',quantity:0.02,unitPrice:45,wasteFactor:1,totalCost:0.9},
      {name:'Brida PVC 4"',unit:'un',quantity:0.05,unitPrice:32,wasteFactor:1,totalCost:1.6},
    ],
    labor:[
      {role:'Plomero',quantity:0.15,dailyWage:155,totalCost:23.25},
      {role:'Peón',quantity:0.1,dailyWage:85,totalCost:8.5},
    ],
    equipment:[],
    dailyOutput:5, crewSize:2, durationDays:0.3,
    children:[],
  },
  {
    id:'res_plumbing_002', code:'INS-004',
    description:'Instalación hidráulica PVC 1/2"',
    unit:'ml', category:'Instalaciones', typology:T.RESIDENCIAL,
    order:24, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0},
    materials:[
      {name:'Tubería PVC hidráulica 1/2" (6m)',unit:'un',quantity:0.17,unitPrice:125,wasteFactor:1.05,totalCost:22.3125},
      {name:'Codo PVC 1/2" x 90°',unit:'un',quantity:0.12,unitPrice:15,wasteFactor:1,totalCost:1.8},
      {name:'Tee PVC 1/2"',unit:'un',quantity:0.08,unitPrice:18,wasteFactor:1,totalCost:1.44},
      {name:'Pegamento PVC (1/4 lt)',unit:'un',quantity:0.02,unitPrice:45,wasteFactor:1,totalCost:0.9},
      {name:'Llave de paso 1/2"',unit:'un',quantity:0.08,unitPrice:45,wasteFactor:1,totalCost:3.6},
    ],
    labor:[
      {role:'Plomero',quantity:0.1,dailyWage:155,totalCost:15.5},
      {role:'Peón',quantity:0.08,dailyWage:85,totalCost:6.8},
    ],
    equipment:[],
    dailyOutput:6, crewSize:2, durationDays:0.2,
    children:[],
  },

  // ═══ ACABADOS ═════════════════════════════════════════════════════════════
  {
    id:'res_finish_001', code:'ACA-001',
    description:'Repello y cernido de muros',
    unit:'m2', category:'Acabados', typology:T.RESIDENCIAL,
    order:25, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,height:0,thickness:0.02},
    materials:[
      {name:'Cemento Portland tipo I 42.5kg',unit:'saco',quantity:0.18,unitPrice:62,wasteFactor:1.05,totalCost:11.718},
      {name:'Cal hidratada 25kg',unit:'saco',quantity:0.12,unitPrice:38,wasteFactor:1,totalCost:4.56},
      {name:'Arena blanca fina (m3)',unit:'m3',quantity:0.015,unitPrice:165,wasteFactor:1,totalCost:2.475},
    ],
    labor:[
      {role:'Albañil',quantity:0.18,dailyWage:145,totalCost:26.1},
      {role:'Peón',quantity:0.1,dailyWage:85,totalCost:8.5},
    ],
    equipment:[],
    dailyOutput:5, crewSize:2, durationDays:0.25,
    children:[],
  },
  {
    id:'res_finish_002', code:'ACA-002',
    description:'Pintura vinílica 2 manos',
    unit:'m2', category:'Acabados', typology:T.RESIDENCIAL,
    order:26, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,height:0,thickness:0},
    materials:[
      {name:'Pintura vinílica interior (galón)',unit:'galón',quantity:0.08,unitPrice:95,wasteFactor:1.05,totalCost:7.98},
      {name:'Sellador acrílico (galón)',unit:'galón',quantity:0.04,unitPrice:75,wasteFactor:1,totalCost:3},
      {name:'Lija No.120 (un)',unit:'un',quantity:0.05,unitPrice:8,wasteFactor:1,totalCost:0.4},
      {name:'Cinta enmascarar (rollo)',unit:'rollo',quantity:0.02,unitPrice:18,wasteFactor:1,totalCost:0.36},
    ],
    labor:[
      {role:'Pintor',quantity:0.1,dailyWage:145,totalCost:14.5},
      {role:'Peón',quantity:0.05,dailyWage:85,totalCost:4.25},
    ],
    equipment:[],
    dailyOutput:6, crewSize:2, durationDays:0.15,
    children:[],
  },
  {
    id:'res_finish_003', code:'ACA-003',
    description:'Piso cerámico 60x60 antideslizante',
    unit:'m2', category:'Acabados', typology:T.RESIDENCIAL,
    order:27, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0},
    materials:[
      {name:'Cerámica 60x60 antideslizante',unit:'m2',quantity:1.05,unitPrice:85,wasteFactor:1.08,totalCost:96.39},
      {name:'Pegamento cerámico saco 25kg',unit:'saco',quantity:0.25,unitPrice:48,wasteFactor:1.05,totalCost:12.6},
      {name:'Fragua color saco 5kg',unit:'saco',quantity:0.1,unitPrice:35,wasteFactor:1,totalCost:3.5},
      {name:'Crucetas 3mm (bolsa)',unit:'bolsa',quantity:0.05,unitPrice:18,wasteFactor:1,totalCost:0.9},
    ],
    labor:[
      {role:'Azulejero',quantity:0.3,dailyWage:165,totalCost:49.5},
      {role:'Peón',quantity:0.15,dailyWage:85,totalCost:12.75},
    ],
    equipment:[],
    dailyOutput:3, crewSize:2, durationDays:0.4,
    children:[],
  },
  {
    id:'res_finish_004', code:'ACA-004',
    description:'Enchape cerámico baños 30x60',
    unit:'m2', category:'Acabados', typology:T.RESIDENCIAL,
    order:28, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,height:0},
    materials:[
      {name:'Cerámica enchape baño 30x60',unit:'m2',quantity:1.08,unitPrice:105,wasteFactor:1.10,totalCost:124.74},
      {name:'Pegamento cerámico saco 25kg',unit:'saco',quantity:0.2,unitPrice:48,wasteFactor:1.05,totalCost:10.08},
      {name:'Fragua color saco 5kg',unit:'saco',quantity:0.08,unitPrice:35,wasteFactor:1,totalCost:2.8},
    ],
    labor:[
      {role:'Azulejero',quantity:0.4,dailyWage:165,totalCost:66},
      {role:'Peón',quantity:0.15,dailyWage:85,totalCost:12.75},
    ],
    equipment:[],
    dailyOutput:2, crewSize:2, durationDays:0.5,
    children:[],
  },
  {
    id:'res_finish_005', code:'ACA-005',
    description:'Cielo falso tabla yeso 1/2"',
    unit:'m2', category:'Acabados', typology:T.RESIDENCIAL,
    order:29, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,thickness:0},
    materials:[
      {name:'Tabla decorativa de yeso 1.22x0.30m',unit:'un',quantity:0.85,unitPrice:65,wasteFactor:1.10,totalCost:57.2},
      {name:'Tornillo para yeso (kg)',unit:'kg',quantity:0.1,unitPrice:35,wasteFactor:1,totalCost:3.5},
      {name:'Masilla para yeso (kg)',unit:'kg',quantity:0.3,unitPrice:28,wasteFactor:1,totalCost:8.4},
    ],
    labor:[
      {role:'Oficial yesero',quantity:0.16,dailyWage:155,totalCost:24.8},
      {role:'Peón',quantity:0.08,dailyWage:85,totalCost:6.8},
    ],
    equipment:[],
    dailyOutput:6, crewSize:2, durationDays:0.3,
    children:[],
  },
  {
    id:'res_finish_006', code:'ACA-006',
    description:'Puerta madera sólida con marco',
    unit:'un', category:'Acabados', typology:T.RESIDENCIAL,
    order:30, isActive:true, projectQuantity:0, computationType:'fixed' as const,
    dimensions:undefined,
    materials:[
      {name:'Puerta madera sólida 0.90x2.10m',unit:'un',quantity:1,unitPrice:1350,wasteFactor:1,totalCost:1350},
      {name:'Marcos y hojas metálicas',unit:'un',quantity:1,unitPrice:350,wasteFactor:1,totalCost:350},
      {name:'Pivotes y cerradura',unit:'un',quantity:1,unitPrice:120,wasteFactor:1,totalCost:120},
      {name:'Pintura esmalte 1/4 gl',unit:'un',quantity:1,unitPrice:45,wasteFactor:1,totalCost:45},
    ],
    labor:[
      {role:'Carpintero',quantity:0.5,dailyWage:165,totalCost:82.5},
      {role:'Peón',quantity:0.25,dailyWage:85,totalCost:21.25},
    ],
    equipment:[],
    dailyOutput:1, crewSize:2, durationDays:0.5,
    children:[],
  },
  {
    id:'res_finish_007', code:'ACA-007',
    description:'Ventana aluminio + vidrio 6mm',
    unit:'m2', category:'Acabados', typology:T.RESIDENCIAL,
    order:31, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,height:0},
    materials:[
      {name:'Perfil aluminio serie 40 (kg)',unit:'kg',quantity:4.5,unitPrice:48,wasteFactor:1.08,totalCost:233.28},
      {name:'Vidrio claro 6mm (m2)',unit:'m2',quantity:0.85,unitPrice:285,wasteFactor:1.08,totalCost:262.98},
      {name:'Silicón sellador (cartucho)',unit:'un',quantity:0.15,unitPrice:35,wasteFactor:1,totalCost:5.25},
      {name:'Tornillo y herrajes',unit:'global',quantity:0.03,unitPrice:85,wasteFactor:1,totalCost:2.55},
    ],
    labor:[
      {role:'Instalador aluminio',quantity:0.3,dailyWage:200,totalCost:60},
      {role:'Ayudante',quantity:0.2,dailyWage:75,totalCost:15},
    ],
    equipment:[],
    dailyOutput:2, crewSize:2, durationDays:0.6,
    children:[],
  },
  {
    id:'res_finish_008', code:'ACA-008',
    description:'Mesón granito cocina',
    unit:'ml', category:'Acabados', typology:T.RESIDENCIAL,
    order:32, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0},
    materials:[
      {name:'Granito pulido (ml)',unit:'ml',quantity:1,unitPrice:680,wasteFactor:1.05,totalCost:714},
      {name:'Pegamento epóxico para piedra (lt)',unit:'lt',quantity:0.3,unitPrice:85,wasteFactor:1,totalCost:25.5},
      {name:'Sellador granito (lt)',unit:'lt',quantity:0.2,unitPrice:65,wasteFactor:1,totalCost:13},
      {name:'Soporte metálico bajo mesón (un)',unit:'un',quantity:0.5,unitPrice:350,wasteFactor:1,totalCost:175},
    ],
    labor:[
      {role:'Marmolista',quantity:1,dailyWage:250,totalCost:250},
      {role:'Ayudante',quantity:0.5,dailyWage:75,totalCost:37.5},
    ],
    equipment:[],
    dailyOutput:1, crewSize:2, durationDays:1.5,
    children:[],
  },

  // ═══ CUBIERTA ═════════════════════════════════════════════════════════════
  {
    id:'res_roof_001', code:'CUB-001',
    description:'Estructura metálica cubierta',
    unit:'kg', category:'Cubierta', typology:T.RESIDENCIAL,
    order:33, isActive:true, projectQuantity:0, computationType:'fixed' as const,
    dimensions:undefined,
    materials:[
      {name:'Perfil C-4x1.5 cal.26 (kg)',unit:'kg',quantity:1.03,unitPrice:17,wasteFactor:1.05,totalCost:18.2805},
      {name:'Perno autoperforante 1/2" (un)',unit:'un',quantity:6,unitPrice:1.2,wasteFactor:1.05,totalCost:7.56},
    ],
    labor:[
      {role:'Techador metálico',quantity:0.05,dailyWage:175,totalCost:8.75},
      {role:'Ayudante',quantity:0.05,dailyWage:75,totalCost:3.75},
    ],
    equipment:[],
    dailyOutput:0.5, crewSize:2, durationDays:0.05,
    children:[],
  },
  {
    id:'res_roof_002', code:'CUB-002',
    description:'Lámina termoacústica calibre 26',
    unit:'m2', category:'Cubierta', typology:T.RESIDENCIAL,
    order:34, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0},
    materials:[
      {name:'Lámina termoacústica cal.26 (m2)',unit:'m2',quantity:1.08,unitPrice:82,wasteFactor:1.07,totalCost:89.8512},
      {name:'Cumbrera metálica (ml)',unit:'ml',quantity:0.08,unitPrice:85,wasteFactor:1.05,totalCost:7.14},
      {name:'Cadena de goteo (ml)',unit:'ml',quantity:0.05,unitPrice:25,wasteFactor:1,totalCost:1.25},
      {name:'Tornillo autoperforante 1" (un)',unit:'un',quantity:6,unitPrice:1.5,wasteFactor:1.05,totalCost:9.45},
    ],
    labor:[
      {role:'Techador especializado',quantity:0.15,dailyWage:165,totalCost:24.75},
      {role:'Ayudante',quantity:0.15,dailyWage:75,totalCost:11.25},
    ],
    equipment:[],
    dailyOutput:4, crewSize:2, durationDays:0.3,
    children:[],
  },
  {
    id:'res_roof_003', code:'CUB-003',
    description:'Canal PVC aguas pluviales',
    unit:'ml', category:'Cubierta', typology:T.RESIDENCIAL,
    order:35, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0},
    materials:[
      {name:'Canal PVC semi-circular 6"',unit:'ml',quantity:1,unitPrice:48,wasteFactor:1.08,totalCost:51.84},
      {name:'Bajada PVC 4"',unit:'ml',quantity:0.5,unitPrice:28,wasteFactor:1.08,totalCost:15.12},
      {name:'Codos PVC 4" x 45°',unit:'un',quantity:0.1,unitPrice:18,wasteFactor:1,totalCost:1.8},
      {name:'Soporte canaleta metálico (un)',unit:'un',quantity:0.2,unitPrice:12,wasteFactor:1,totalCost:2.4},
    ],
    labor:[
      {role:'Ayudante plomero',quantity:0.2,dailyWage:85,totalCost:17},
    ],
    equipment:[],
    dailyOutput:6, crewSize:1, durationDays:0.4,
    children:[],
  },

  // ═══ EXTERIORES ════════════════════════════════════════════════════════════
  {
    id:'res_exterior_001', code:'EXT-001',
    description:'Acera perimetral concreto e=0.10m',
    unit:'m2', category:'Exteriores', typology:T.RESIDENCIAL,
    order:36, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,thickness:0.10},
    materials:[
      {name:"Concreto f'c 250",unit:'m3',quantity:0.1,unitPrice:540,wasteFactor:1.03,totalCost:55.62},
      {name:'Cemento Portland 42.5kg',unit:'saco',quantity:1.0,unitPrice:62,wasteFactor:1.02,totalCost:63.24},
      {name:'Arena de río lavada',unit:'m3',quantity:0.05,unitPrice:185,wasteFactor:1,totalCost:9.25},
      {name:'Grava triturada 3/4"',unit:'m3',quantity:0.07,unitPrice:210,wasteFactor:1,totalCost:14.7},
      {name:'Malla electrosoldada 6x6-10/10',unit:'m2',quantity:1.05,unitPrice:45,wasteFactor:1,totalCost:47.25},
    ],
    labor:[
      {role:'Maestro de obras',quantity:0.12,dailyWage:185,totalCost:22.2},
      {role:'Albañil',quantity:0.2,dailyWage:145,totalCost:29},
      {role:'Peón',quantity:0.3,dailyWage:85,totalCost:25.5},
    ],
    equipment:[],
    dailyOutput:10, crewSize:3, durationDays:0.2,
    children:[],
  },
  {
    id:'res_exterior_002', code:'EXT-002',
    description:'Jardinización y siembra de grama',
    unit:'m2', category:'Exteriores', typology:T.RESIDENCIAL,
    order:37, isActive:true, projectQuantity:0, computationType:'fixed' as const,
    dimensions:undefined,
    materials:[
      {name:'Tierra negra para jardín (m3)',unit:'m3',quantity:0.1,unitPrice:120,wasteFactor:1.05,totalCost:12.6},
      {name:'Gramilla (m2)',unit:'m2',quantity:1,unitPrice:35,wasteFactor:1.08,totalCost:37.8},
      {name:'Fertilizante 15-15-15 (kg)',unit:'kg',quantity:0.5,unitPrice:28,wasteFactor:1,totalCost:14},
      {name:'Rollo de pasto (m2)',unit:'m2',quantity:1,unitPrice:12,wasteFactor:1,totalCost:12},
    ],
    labor:[
      {role:'Jardinero',quantity:0.1,dailyWage:100,totalCost:10},
      {role:'Peón',quantity:0.1,dailyWage:85,totalCost:8.5},
    ],
    equipment:[],
    dailyOutput:8, crewSize:2, durationDays:0.1,
    children:[],
  },
  {
    id:'res_exterior_003', code:'EXT-003',
    description:'Portón metálico de acceso',
    unit:'un', category:'Exteriores', typology:T.RESIDENCIAL,
    order:38, isActive:true, projectQuantity:0, computationType:'fixed' as const,
    dimensions:undefined,
    materials:[
      {name:'Estructura metálica portón (kg)',unit:'kg',quantity:45,unitPrice:22,wasteFactor:1.05,totalCost:1039.5},
      {name:'Lámina calibre 14 para portón (m2)',unit:'m2',quantity:4,unitPrice:85,wasteFactor:1.08,totalCost:367.2},
      {name:'Pivotes y bisagras',unit:'un',quantity:2,unitPrice:185,wasteFactor:1,totalCost:370},
      {name:'Cerradura de seguridad',unit:'un',quantity:1,unitPrice:350,wasteFactor:1,totalCost:350},
      {name:'Pintura esmalte anticorrosiva (lt)',unit:'lt',quantity:2,unitPrice:85,wasteFactor:1.10,totalCost:187},
    ],
    labor:[
      {role:'Herrero',quantity:1.5,dailyWage:250,totalCost:375},
      {role:'Ayudante',quantity:1,dailyWage:85,totalCost:85},
      {role:'Pintor',quantity:0.5,dailyWage:145,totalCost:72.5},
    ],
    equipment:[],
    dailyOutput:1, crewSize:3, durationDays:2,
    children:[],
  },
  {
    id:'res_exterior_004', code:'EXT-004',
    description:'Limpieza final y entrega de obra',
    unit:'global', category:'Exteriores', typology:T.RESIDENCIAL,
    order:39, isActive:true, projectQuantity:0, computationType:'fixed' as const,
    dimensions:undefined,
    materials:[
      {name:'Productos de limpieza industrial',unit:'global',quantity:1,unitPrice:250,wasteFactor:1,totalCost:250},
    ],
    labor:[
      {role:'Personal de limpieza',quantity:2,dailyWage:85,totalCost:170},
    ],
    equipment:[],
    dailyOutput:1, crewSize:3, durationDays:1,
    children:[],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
//  COMERCIAL — 3 renglones
// ═══════════════════════════════════════════════════════════════════════════════
export const COMERCIAL_LINES: BudgetLineDocument[] = [
  {
    id:'com_foundation_001', code:'COM-CIM-001',
    description:'Cimentación - Excavación mecánica',
    unit:'m³', category:'Cimentación', typology:T.COMERCIAL,
    order:1, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,height:0},
    materials:[
      {name:'Combustible diesel retroexcavadora',unit:'galón',quantity:2,unitPrice:32,wasteFactor:1.06,totalCost:67.84},
      {name:'Operador retroexcavadora (día)',unit:'día',quantity:0.5,unitPrice:185,wasteFactor:1,totalCost:92.5},
    ],
    labor:[
      {role:'Operador retroexcavadora',quantity:0.1,dailyWage:185,totalCost:18.5},
      {role:'Peón',quantity:0.1,dailyWage:85,totalCost:8.5},
    ],
    equipment:[],
    dailyOutput:10, crewSize:2, durationDays:0,
    children:[],
  },
  {
    id:'com_platea_001', code:'COM-CIM-002',
    description:"Platea de cimentación f'c=280 kg/cm² e=0.25m",
    unit:'m²', category:'Cimentación', typology:T.COMERCIAL,
    order:2, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,thickness:0.25},
    materials:[
      {name:"Concreto f'c 280",unit:'m³',quantity:0.25,unitPrice:560,wasteFactor:1.04,totalCost:145.6},
      {name:'Cemento Portland 50kg',unit:'saco',quantity:3.0,unitPrice:65,wasteFactor:1.03,totalCost:200.85},
      {name:'Arena de río lavada',unit:'m3',quantity:0.14,unitPrice:185,wasteFactor:1,totalCost:25.9},
      {name:'Grava triturada 3/4"',unit:'m3',quantity:0.21,unitPrice:210,wasteFactor:1,totalCost:44.1},
      {name:'Malla electrosoldada 6x6-10/10',unit:'m2',quantity:1.05,unitPrice:45,wasteFactor:1,totalCost:47.25},
      {name:'Aditivo impermeabilizante',unit:'lt',quantity:0.5,unitPrice:120,wasteFactor:1,totalCost:60},
    ],
    labor:[
      {role:'Maestro de obras',quantity:0.15,dailyWage:185,totalCost:27.75},
      {role:'Albañil',quantity:0.3,dailyWage:145,totalCost:43.5},
      {role:'Peón',quantity:0.6,dailyWage:85,totalCost:51},
    ],
    equipment:[],
    dailyOutput:4, crewSize:4, durationDays:0.5,
    children:[],
  },
  {
    id:'com_facade_001', code:'COM-FAC-001',
    description:'Fachada - Muro cortina aluminio + vidrio',
    unit:'m²', category:'Fachada', typology:T.COMERCIAL,
    order:3, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,height:0},
    materials:[
      {name:'Perfil aluminio serie 50 (kg)',unit:'kg',quantity:8.5,unitPrice:48,wasteFactor:1.08,totalCost:440.64},
      {name:'Vidrio templado 6mm (m2)',unit:'m2',quantity:0.85,unitPrice:285,wasteFactor:1.08,totalCost:262.98},
      {name:'Sellador estructural (cartucho)',unit:'un',quantity:0.5,unitPrice:85,wasteFactor:1,totalCost:42.5},
      {name:'Tornillería inoxidable (global)',unit:'global',quantity:0.02,unitPrice:185,wasteFactor:1,totalCost:3.7},
    ],
    labor:[
      {role:'Instalador aluminio y vidrio',quantity:0.5,dailyWage:245,totalCost:122.5},
      {role:'Ayudante',quantity:0.3,dailyWage:85,totalCost:25.5},
    ],
    equipment:[],
    dailyOutput:2, crewSize:3, durationDays:1,
    children:[],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
//  INDUSTRIAL — 3 renglones
// ═══════════════════════════════════════════════════════════════════════════════
export const INDUSTRIAL_LINES: BudgetLineDocument[] = [
  {
    id:'ind_foundation_001', code:'IND-CIM-001',
    description:'Cimentación - Excavación Industrial',
    unit:'m³', category:'Cimentación', typology:T.INDUSTRIAL,
    order:1, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,height:0},
    materials:[
      {name:'Combustible diesel retroexcavadora',unit:'galón',quantity:3,unitPrice:32,wasteFactor:1.08,totalCost:103.68},
      {name:'Operador retroexcavadora industrial',unit:'global',quantity:0.5,unitPrice:185,wasteFactor:1,totalCost:92.5},
    ],
    labor:[
      {role:'Operador retroexcavadora',quantity:0.05,dailyWage:185,totalCost:9.25},
    ],
    equipment:[],
    dailyOutput:15, crewSize:2, durationDays:0,
    children:[],
  },
  {
    id:'ind_platea_001', code:'IND-CIM-002',
    description:"Platea industrial f'c=280 kg/cm² e=0.20m",
    unit:'m²', category:'Cimentación', typology:T.INDUSTRIAL,
    order:2, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,thickness:0.20},
    materials:[
      {name:"Concreto industrial f'c 280",unit:'m³',quantity:0.20,unitPrice:620,wasteFactor:1.05,totalCost:130.2},
      {name:'Cemento Portland 50kg',unit:'saco',quantity:2.4,unitPrice:65,wasteFactor:1.03,totalCost:160.68},
      {name:'Arena de río lavada',unit:'m3',quantity:0.10,unitPrice:185,wasteFactor:1,totalCost:18.5},
      {name:'Grava triturada 3/4"',unit:'m3',quantity:0.15,unitPrice:210,wasteFactor:1,totalCost:31.5},
      {name:'Malla electrosoldada 6x6-6/6',unit:'m2',quantity:1.05,unitPrice:28,wasteFactor:1,totalCost:29.4},
      {name:'Aditivo endurecedor de piso (kg)',unit:'kg',quantity:0.8,unitPrice:120,wasteFactor:1,totalCost:96},
    ],
    labor:[
      {role:'Maestro de obras',quantity:0.08,dailyWage:185,totalCost:14.8},
      {role:'Albañil',quantity:0.15,dailyWage:145,totalCost:21.75},
      {role:'Peón',quantity:0.3,dailyWage:85,totalCost:25.5},
    ],
    equipment:[],
    dailyOutput:6, crewSize:4, durationDays:0.3,
    children:[],
  },
  {
    id:'ind_cubierta_001', code:'IND-CUB-001',
    description:'Cubierta - Lámina termoacústica + estructura',
    unit:'m²', category:'Cubierta', typology:T.INDUSTRIAL,
    order:5, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0},
    materials:[
      {name:'Lámina termoacústica cal.28 (m2)',unit:'m2',quantity:1.10,unitPrice:185,wasteFactor:1.07,totalCost:216.95},
      {name:'Correa metálica C-150 (kg)',unit:'kg',quantity:0.85,unitPrice:48,wasteFactor:1.07,totalCost:43.752},
      {name:'Tornillo autoperforante 1" (un)',unit:'un',quantity:8,unitPrice:1.8,wasteFactor:1.05,totalCost:15.12},
      {name:'Canaleta metálica (ml)',unit:'ml',quantity:0.5,unitPrice:55,wasteFactor:1,totalCost:27.5},
    ],
    labor:[
      {role:'Techador especializado',quantity:0.15,dailyWage:165,totalCost:24.75},
      {role:'Ayudante',quantity:0.15,dailyWage:95,totalCost:14.25},
    ],
    equipment:[],
    dailyOutput:5, crewSize:3, durationDays:0.3,
    children:[],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
//  CIVIL — 3 renglones
// ═══════════════════════════════════════════════════════════════════════════════
export const CIVIL_LINES: BudgetLineDocument[] = [
  {
    id:'civ_road_001', code:'CIV-VIA-001',
    description:'Carretera - Excavación y Relleno',
    unit:'m³', category:'Movimiento de Tierras', typology:T.CIVIL,
    order:1, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,height:0},
    materials:[
      {name:'Excavación con maquinaria (bulldozer)',unit:'global',quantity:1,unitPrice:350,wasteFactor:1.12,totalCost:392},
      {name:'Diesel equipos pesados (galón)',unit:'galón',quantity:5,unitPrice:35,wasteFactor:1,totalCost:175},
    ],
    labor:[
      {role:'Operador retroexcavadora',quantity:0.03,dailyWage:185,totalCost:5.55},
      {role:'Peón',quantity:0.05,dailyWage:85,totalCost:4.25},
    ],
    equipment:[],
    dailyOutput:30, crewSize:2, durationDays:0.03,
    children:[],
  },
  {
    id:'civ_road_002', code:'CIV-VIA-002',
    description:'Carretera - Sub-base Granular',
    unit:'m²', category:'Pavimento', typology:T.CIVIL,
    order:2, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,thickness:0.30},
    materials:[
      {name:'Material granular sub-base (m3)',unit:'m3',quantity:0.3,unitPrice:85,wasteFactor:1.10,totalCost:28.05},
      {name:'Compactación vibrocompactador (global)',unit:'global',quantity:1,unitPrice:25,wasteFactor:1,totalCost:25},
    ],
    labor:[
      {role:'Operador vibrocompactador',quantity:0.05,dailyWage:185,totalCost:9.25},
    ],
    equipment:[],
    dailyOutput:20, crewSize:2, durationDays:0.05,
    children:[],
  },
  {
    id:'civ_bridge_001', code:'CIV-EST-001',
    description:"Puente - Pilas de Concreto f'c=400 kg/cm²",
    unit:'m³', category:'Estructuras', typology:T.CIVIL,
    order:4, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,height:0},
    materials:[
      {name:"Concreto f'c 400",unit:'m³',quantity:1,unitPrice:700,wasteFactor:1.06,totalCost:742},
      {name:'Cemento Portland 50kg',unit:'saco',quantity:10,unitPrice:65,wasteFactor:1.03,totalCost:669.5},
      {name:'Arena de río lavada',unit:'m3',quantity:0.45,unitPrice:185,wasteFactor:1,totalCost:83.25},
      {name:'Grava triturada 3/4"',unit:'m3',quantity:0.65,unitPrice:210,wasteFactor:1,totalCost:136.5},
      {name:'Acero de refuerzo No.5 (5/8") (kg)',unit:'kg',quantity:120,unitPrice:14,wasteFactor:1.05,totalCost:1764},
      {name:'Formaleta metálica (m2)',unit:'m2',quantity:20,unitPrice:85,wasteFactor:1.02,totalCost:1734},
      {name:'Desmoldante (lt)',unit:'lt',quantity:1,unitPrice:28,wasteFactor:1,totalCost:28},
    ],
    labor:[
      {role:'Maestro de obras',quantity:0.5,dailyWage:185,totalCost:92.5},
      {role:'Albañil',quantity:0.8,dailyWage:145,totalCost:116},
      {role:'Acerista',quantity:0.6,dailyWage:165,totalCost:99},
      {role:'Peón',quantity:3,dailyWage:85,totalCost:255},
    ],
    equipment:[],
    dailyOutput:0.5, crewSize:5, durationDays:2,
    children:[],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
//  PÚBLICA — 2 renglones
// ═══════════════════════════════════════════════════════════════════════════════
export const PUBLICA_LINES: BudgetLineDocument[] = [
  {
    id:'pub_foundation_001', code:'PUB-CIM-001',
    description:'Cimentación - Excavación Controlada',
    unit:'m³', category:'Cimentación', typology:T.PUBLICA,
    order:1, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0,height:0},
    materials:[
      {name:'Excavación controlada (m3)',unit:'m3',quantity:1,unitPrice:30,wasteFactor:1.07,totalCost:32.1},
      {name:'Retiro de material (carro)',unit:'global',quantity:1,unitPrice:150,wasteFactor:1,totalCost:150},
    ],
    labor:[
      {role:'Peón',quantity:0.6,dailyWage:85,totalCost:51},
    ],
    equipment:[],
    dailyOutput:4, crewSize:3, durationDays:0,
    children:[],
  },
  {
    id:'pub_escuela_001', code:'PUB-EST-001',
    description:'Aula escolar - Estructura concreto (módulo 7x8m)',
    unit:'m²', category:'Estructura', typology:T.PUBLICA,
    order:3, isActive:true, projectQuantity:0, computationType:'dynamic' as const,
    dimensions:{length:0,width:0},
    materials:[
      {name:"Concreto f'c 280",unit:'m²',quantity:1,unitPrice:575,wasteFactor:1.04,totalCost:598},
      {name:'Cemento Portland 50kg',unit:'saco',quantity:3.2,unitPrice:65,wasteFactor:1.03,totalCost:210.08},
      {name:'Arena de río lavada',unit:'m3',quantity:0.16,unitPrice:185,wasteFactor:1,totalCost:29.6},
      {name:'Grava triturada 3/4"',unit:'m3',quantity:0.23,unitPrice:210,wasteFactor:1,totalCost:48.3},
      {name:'Acero de refuerzo No.4 (1/2") (kg)',unit:'kg',quantity:22,unitPrice:10,wasteFactor:1.05,totalCost:231},
      {name:'Bloque de pómez No.5 (un)',unit:'un',quantity:12,unitPrice:5.5,wasteFactor:1.05,totalCost:69.3},
    ],
    labor:[
      {role:'Maestro de obras',quantity:0.3,dailyWage:185,totalCost:55.5},
      {role:'Albañil',quantity:0.8,dailyWage:145,totalCost:116},
      {role:'Peón',quantity:1.5,dailyWage:85,totalCost:127.5},
    ],
    equipment:[],
    dailyOutput:1, crewSize:5, durationDays:1.5,
    children:[],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
//  COMBINED DEFAULT BUDGET
// ═══════════════════════════════════════════════════════════════════════════════
export const defaultBudget = [...RESIDENCIAL_LINES, ...COMERCIAL_LINES, ...INDUSTRIAL_LINES, ...CIVIL_LINES, ...PUBLICA_LINES];

export function getBudgetLinesByTypology(typology: string) {
  return defaultBudget.filter(l => !l.typology || String(l.typology) === typology);
}

export function getAvailableTypologies(): string[] {
  return Array.from(new Set(defaultBudget.map(l => String(l.typology)).filter(Boolean)));
}